//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Product_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Descr { get; set; }
        public decimal Product_price { get; set; }
        public Nullable<int> Product_CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
